<a href="https://colab.research.google.com/github/habutaha/Cluster-champs_final-project_dsml2021/blob/HazemAbutaha/TechFunding_deep_learning_building_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature engineering for Tech Funding Data

## import data and libraries

In [76]:
import pandas as pd
# MinMax Sclaer will convert a sequence of number and scale to a range between 0 and 1.
# for example, if the smallest and biggest numbers in a dataset are 20,000 and 100,000
# MinMaxScaler will convert these to 0 and 1
from sklearn.preprocessing import MinMaxScaler

In [77]:
trainDf = pd.read_csv('./techFunding_train.csv')
testDf = pd.read_csv('./techFunding_test.csv')

In [78]:
# dropping the comapny name
trainDf.drop('Company', axis=1, inplace=True)
testDf.drop('Company', axis=1, inplace=True)

In [79]:
trainDf.head()

   Funding Amount (USD)  ...  Vertical_Wellness
0            16000000.0  ...                  0
1            10000000.0  ...                  0
2             1500000.0  ...                  0
3            50000000.0  ...                  0
4            25000000.0  ...                  0

[5 rows x 165 columns]

In [80]:
#instantiate the sclaer
scaler = MinMaxScaler(feature_range=(0,1))

In [81]:
# .fit_transform() will apply, (1) feature engineering, (2) training and (3) validation in 1 method_
train_scaled = scaler.fit_transform(trainDf)
test_scaled = scaler.fit_transform(testDf)

In [82]:
train_scaled

array([[0.00839378, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00523823, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00076785, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00786786, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01417897, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0147049 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [83]:
test_scaled

array([[0.01650275, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.46941683, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01983664, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.07484581, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05317553, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00235039, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [84]:
# print the numbers that were used to scale the data
print(
    "Multiply by {:.10f} and Add {:.10f}".format(
        scaler.scale_[0],
        scaler.min_[0]
        )
)
# Multiply by 0.0000000017 and Add -0.0001666944

Multiply by 0.0000000017 and Add -0.0001666944

In [85]:
# export the scales data for the next notebook
trainDf_scaled = pd.DataFrame(train_scaled, columns=trainDf.columns.values)
testDf_scaled = pd.DataFrame(test_scaled, columns=testDf.columns.values)

# Deep Learning for predicting Tech companies Funding

### Import Data and Libraries

In [86]:
import pandas as pd

from keras.models import Sequential
# Sequential will be used to create the three
# layers of neural networks: 
# (1) Input Layer, (2) Hiddens Layers, and (3) Output Layer

# Use '*' to import all three types of layers
from keras.layers import *

In [87]:
trainDf = trainDf_scaled
trainDf.head()

   Funding Amount (USD)  ...  Vertical_Wellness
0              0.008394  ...                0.0
1              0.005238  ...                0.0
2              0.000768  ...                0.0
3              0.026275  ...                0.0
4              0.013127  ...                0.0

[5 rows x 165 columns]

In [88]:
# Use .value attribute to extract features as NumPy array
features = trainDf.drop('Funding Amount (USD)', axis=1, inplace=False).values

# Note: two square brackets because this is a Pandas DataFrame (i.e, multidimensiona;)
label = trainDf[['Funding Amount (USD)']].values

### Building the Neural Network

In [89]:
# Instantiate the Sequential class
modelDL = Sequential()

# Add the Input Layer
# Note:
# Dense: is the neural network architecture type
# input_dim: is the number of features
# activation: is the activation function ReLU (Rectified Linear Unit)
modelDL.add( Dense(50, input_dim=164, activation='relu') )

# Add the Hidden Layers
    # the first hidden layer
modelDL.add( Dense(100, activation='relu') )
    # The second hidden layer
modelDL.add( Dense(50, activation='relu') )

# Add the Output Layerswd
modelDL.add( Dense(1, activation='linear') )

# Compile the Deep Learning model
modelDL.compile(loss='mean_squared_error', optimizer='adam')

### Train, Validation, and Test

In [90]:
# Note:
# features is the array of explanatory (random) variables
# label is the array of response (random) variable
# epochs is the number of times to feed the entire data to the model
# shuffle will randomize the features
# verbose will control the logging of TensorFlow

# Here .fit() will train and validate the model
modelDL.fit( features, label, epochs=50, shuffle=True, verbose=20)

Epoch 1/50
Epoch 2/50
Epoch 3/50
Epoch 4/50
Epoch 5/50
Epoch 6/50
Epoch 7/50
Epoch 8/50
Epoch 9/50
Epoch 10/50
Epoch 11/50
Epoch 12/50
Epoch 13/50
Epoch 14/50
Epoch 15/50
Epoch 16/50
Epoch 17/50
Epoch 18/50
Epoch 19/50
Epoch 20/50
Epoch 21/50
Epoch 22/50
Epoch 23/50
Epoch 24/50
Epoch 25/50
Epoch 26/50
Epoch 27/50
Epoch 28/50
Epoch 29/50
Epoch 30/50
Epoch 31/50
Epoch 32/50
Epoch 33/50
Epoch 34/50
Epoch 35/50
Epoch 36/50
Epoch 37/50
Epoch 38/50
Epoch 39/50
Epoch 40/50
Epoch 41/50
Epoch 42/50
Epoch 43/50
Epoch 44/50
Epoch 45/50
Epoch 46/50
Epoch 47/50
Epoch 48/50
Epoch 49/50
Epoch 50/50

In [91]:
# Import the Test Dataset
testDf = testDf_scaled

In [92]:
# Select the features and label for test dataset
features_test = testDf.drop('Funding Amount (USD)', axis=1).values
label_test = testDf[['Funding Amount (USD)']].values

In [93]:
# Evaluate the model before prediction. this will allows
#us to optimize the hyperparameters if necessary.

# Note:
# MSE is ranged between [0, +infinity)
metric_mse = modelDL.evaluate(features_test, label_test, verbose=0)

In [94]:
# Print the MSE after evaluation
print(" The MSE (Mean Squared Error): {}".format(metric_mse))

 The MSE (Mean Squared Error): 0.014629501849412918

In [95]:
# Convert from scintific notation to float
print('%f' % metric_mse )

0.014630